version: "3"
services:
  kurento:
    image: kurento/kurento-media-server:xenial-latest
    ports:
      - "8888:8888"
    container_name: kurento
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: myapp
    environment:
      KMS_HOST: ws://kurento:8888/kurento
    entrypoint: ["java","-jar","kurento-hello-world-6.8.0-exec.jar"]
    depends_on:
      - kurento
